#!/bin/bash

if [ $# -eq 3 ]; then
    git add .
    git commit -m "$1"
    git push --set-upstream $2 $3
elif [ $# -eq 1 ]; then
    git add .
    git commit -m "$1"
    git push
else
    echo "You need to provide at least 1 argument"
fi
